version: "2.4"
services:
  achal01:
    hostname: achal01
    build: 
      context: .
      network: host
    networks:
      app_net:
        ipv4_address: 198.162.55.144
    cap_add:
      - SYS_NICE
  achal02:
    hostname: achal02
    build: 
      context: .
      network: host
    networks:
      app_net:
        ipv4_address: 198.162.55.145
    cap_add:
      - SYS_NICE
  achal03:
    hostname: achal03
    build: 
      context: .
      network: host
    networks:
      app_net:
        ipv4_address: 198.162.55.146
    cap_add:
      - SYS_NICE
  achal04:
    hostname: achal04
    build: 
      context: .
      network: host
    networks:
      app_net:
        ipv4_address: 198.162.55.147
    cap_add:
      - SYS_NICE
  client:
    hostname: client
    build: 
      context: .
      network: host
      dockerfile: Dockerfile.client
    networks:
      app_net:
        ipv4_address: 198.162.55.128
    volumes:
      - "./logging:/root/logging"
      - "./paper:/root/paper"
    command: |-
      bash -c '
        echo "" > /root/.ssh/known_hosts;
        for i in 1 2 3 4; do
          while ! ssh achal0$${i} echo achal0$${i} is up; 
          do 
            sleep 1; 
          done;
        done;
        sleep 3;
        rm -rf logging/*;
        CONTAINER_MODE=true bash run_ivp_2.sh;
        bash plot_ivp_2.sh;
        echo Experiment Done!;
        tail -f /dev/null;
      '

networks:
  app_net:
    driver: bridge
    ipam:
     config:
       - subnet: 198.162.55.0/24
         gateway: 198.162.55.1